-- MySQL Script generated by MySQL Workbench
-- Thu Jan  2 00:00:14 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema post-it
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema post-it
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `post-it` DEFAULT CHARACTER SET utf8 ;
USE `post-it` ;

-- -----------------------------------------------------
-- Table `post-it`.`file`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `post-it`.`file` (
  `file_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `type` VARCHAR(255) NOT NULL,
  `original_name` VARCHAR(255) NOT NULL,
  `extension` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`file_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `post-it`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `post-it`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `token` VARCHAR(255) NULL,
  `token_expiry_date` DATETIME NULL,
  `enabled` TINYINT NOT NULL,
  `file_id` INT NULL,
  `follows` LONGTEXT NULL,
  `followers` LONGTEXT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `users_file_idx` (`file_id` ASC) VISIBLE,
  CONSTRAINT `users_file`
    FOREIGN KEY (`file_id`)
    REFERENCES `post-it`.`file` (`file_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `post-it`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `post-it`.`post` (
  `post_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `file_id` INT NULL,
  `message` VARCHAR(255) NULL,
  `likes` LONGTEXT NULL,
  `date` DATETIME NULL,
  PRIMARY KEY (`post_id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `post_comment_idx` (`file_id` ASC) VISIBLE,
  CONSTRAINT `post_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `post-it`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `post_file`
    FOREIGN KEY (`file_id`)
    REFERENCES `post-it`.`file` (`file_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `post-it`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `post-it`.`comment` (
  `comment_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `post_id` INT NOT NULL,
  `text` VARCHAR(255) NOT NULL,
  `date` DATETIME NULL,
  PRIMARY KEY (`comment_id`),
  INDEX `comment_users_idx` (`user_id` ASC) VISIBLE,
  INDEX `comment_post_idx` (`post_id` ASC) VISIBLE,
  CONSTRAINT `comment_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `post-it`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `comment_post`
    FOREIGN KEY (`post_id`)
    REFERENCES `post-it`.`post` (`post_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `post-it`.`user_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `post-it`.`user_roles` (
  `user_roles_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_roles_id`),
  INDEX `user_role_users_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `user_role_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `post-it`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
